### ISSUE TITLE
only shows the status of one battery

### ISSUE THREAD

**Issue by keis** [kevva/linux-battery#1]
My machine has two batteries this module however only returns the information about BAT0. The name of all batteries can be found by filtering the output of `upower -e`

I think the api would have to be changed to return a list to support this however, wdyt?

**Comment by sindresorhus** [comment]
It should take into account all the batteries, but only show the total power / number of batteries.

**Comment by kevva** [comment]
Is it prefixed with `battery_` too?

**Comment by keis** [comment]
yup. it looks like this

```
/org/freedesktop/UPower/devices/line_power_AC
/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/battery_BAT1
/org/freedesktop/UPower/devices/DisplayDevice
```

**Comment by kevva** [comment]
Fixed now. Install `2.0.0`.

**Comment by keis** [comment]
I see both batteries now.

cheers!
